# Springboot config
spring:
  application:
    name: notification-service
  sleuth:
    integration:
      enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 15
