spring:
  application:
    name: management-assignment-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 15