#setup current server and port
server:
  port: 0

#setup current library
spring:
  application:
    name: partner-service
  profiles:
    active: dev
  zipkin:
    base-url: http://localhost:9411

#setup service discovery eureka
eureka:
  instance:
    status-page-url-path: /actuator/health
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

