version: '3.8'
services:

  postgres-db:
    container_name: postgres-db
    image: postgres:11.4-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdf1234A

  zipkin-dc:
    container_name: zipkin-distributed-tracing
    image: openzipkin/zipkin
    restart: always
    ports:
      - "9411:9411"