#setup current library
spring:
  application:
    name: user-service
  profiles:
    active: dev

#setup service discovery eureka
eureka:
  instance:
    status-page-url-path: /actuator/health
    hostname: localhost
  client:
    region: ID-Bandung - Batununggal
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

# Management Actuator Endpoint
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
