#setup current server and port
server:
  port: 8761
spring:
  zipkin:
    base-url: http://localhost:9411
    enabled: false
  sleuth:
    sampler:
      probability: 1.0
  profiles:
    active: dev

#setup eureka stand alone
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 0
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  datacenter: talent-management-system
  environment: development
  server:
    enable-self-preservation: true

#setup eureka account
app:
  eureka:
    username: eureka
    password: password