#setup current server and port
server:
  port: 8761
spring:
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://localhost:9411
    enabled: false
  sleuth:
    sampler:
      probability: 1.0
  profiles:
    active: dev

#setup eureka account
app:
  eureka:
    username: eureka
    password: password