#setup current server and port
server:
  port: 8761
spring:
  sleuth:
    sampler:
      probability: 1.0
  profiles:
    active: default

#setup eureka stand alone
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 0
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
    region: ID-Bandung - Batununggal
  datacenter: TALENT MANAGEMENT SYSTEM
  environment: development
  server:
    enable-self-preservation: true

# Management Actuator Endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"