#setup current library
spring:
  application:
    name: talent-management-service
  profiles:
    active: dev
  zipkin:
    base-url: http://localhost:9411

#setup service discovery eureka
eureka:
  instance:
    status-page-url-path: /actuator/health
    hostname: localhost
  client:
    region: ID-Bandung - Batununggal
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

