server:
  port: 8081

#setup service discovery eureka
eureka:
  instance:
    status-page-url-path: /actuator/health
    hostname: localhost
  client:
    region: ID-Bandung - Batununggal
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
  sleuth:
    sampler:
      probability: 1.0
  profiles:
    active: dev
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: partner-service
          uri: lb://partner-service # load balancer
          predicates:
            - Path=/api/v1/partner/**,/api/v2/partner/**
logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
